openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/health/:
    get:
      operationId: health_retrieve
      description: |-
        Return service status.

        Args:
            request (Request): The incoming request instance.
            *args: Unused positional arguments.
            **kwargs: Unused keyword arguments.

        Returns:
            Response: JSON body {"status": "ok"} with HTTP 200.
      tags:
      - health
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - bearerAuth: []
      - bearerAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      security:
      - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      security:
      - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/users/:
    get:
      operationId: users_list
      description: |-
        User operations.

        Provides create, retrieve, list, update, partial_update, and destroy.
      tags:
      - users
      security:
      - bearerAuth: []
      - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
    post:
      operationId: users_create
      description: |-
        User operations.

        Provides create, retrieve, list, update, partial_update, and destroy.
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - bearerAuth: []
      - bearerAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/{id}/:
    get:
      operationId: users_retrieve
      description: |-
        User operations.

        Provides create, retrieve, list, update, partial_update, and destroy.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      security:
      - bearerAuth: []
      - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: users_update
      description: |-
        User operations.

        Provides create, retrieve, list, update, partial_update, and destroy.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      security:
      - bearerAuth: []
      - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUpdate'
          description: ''
    patch:
      operationId: users_partial_update
      description: |-
        User operations.

        Provides create, retrieve, list, update, partial_update, and destroy.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserUpdate'
      security:
      - bearerAuth: []
      - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUpdate'
          description: ''
    delete:
      operationId: users_destroy
      description: |-
        User operations.

        Provides create, retrieve, list, update, partial_update, and destroy.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - users
      security:
      - bearerAuth: []
      - bearerAuth: []
      responses:
        '204':
          description: No response body
  /api/users/ids/:
    get:
      operationId: users_ids_retrieve
      description: |-
        List all user IDs.

        Args:
            request (Request): The incoming request instance.

        Returns:
            Response: A list of user IDs (strings).
      tags:
      - users
      security:
      - bearerAuth: []
      - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    HealthCheck:
      type: object
      description: |-
        Serializer for the health check response.

        Fields:
            status (CharField): Service status string (e.g., "ok").
      properties:
        status:
          type: string
      required:
      - status
    PatchedUserUpdate:
      type: object
      description: |-
        Serializer for updating users with strict id immutability.

        - `id` is read-only.
        - If `id` appears in the request body, return 400 with a clear error.
      properties:
        id:
          type: string
          readOnly: true
          description: Israeli ID (string, 5-9 digits, valid checksum)
        name:
          type: string
          description: Full name (required).
          maxLength: 100
        phone:
          type: string
          description: Phone number in E.164 format (e.g., +972...).
          maxLength: 20
        address:
          type: string
          description: Street address (required).
          maxLength: 255
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    User:
      type: object
      description: Serializer for the User model.
      properties:
        id:
          type: string
          description: Israeli ID (string, 5-9 digits, valid checksum)
          maxLength: 9
        name:
          type: string
          description: Full name (required).
          maxLength: 100
        phone:
          type: string
          description: Phone number in E.164 format (e.g., +972...).
          maxLength: 20
        address:
          type: string
          description: Street address (required).
          maxLength: 255
      required:
      - address
      - id
      - name
      - phone
    UserUpdate:
      type: object
      description: |-
        Serializer for updating users with strict id immutability.

        - `id` is read-only.
        - If `id` appears in the request body, return 400 with a clear error.
      properties:
        id:
          type: string
          readOnly: true
          description: Israeli ID (string, 5-9 digits, valid checksum)
        name:
          type: string
          description: Full name (required).
          maxLength: 100
        phone:
          type: string
          description: Phone number in E.164 format (e.g., +972...).
          maxLength: 20
        address:
          type: string
          description: Street address (required).
          maxLength: 255
      required:
      - address
      - id
      - name
      - phone
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
