name: "🛠️ CI"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  static_code_analysis:
    uses: sidkos/metadata_server/.github/workflows/static_code_analysis.yml@authentication
    with:
      build_and_install_script: "./scripts/build_and_install_open_api_client.sh"
    secrets: inherit

  openapi-validation:
    uses: sidkos/metadata_server/.github/workflows/openapi_validation.yml@authentication
    with:
      open_api_spec_file: "src/open_api_spec.yml"
    secrets: inherit

  unit-tests:
    uses: sidkos/metadata_server/.github/workflows/unit_tests_on_docker.yml@authentication
    with:
      compose_file_path: 'docker-compose.yml'
      tests_host_name: 'metadata_manager'
      build_and_install_script: "./scripts/build_and_install_open_api_client.sh"
    secrets: inherit
