name: "🛠️ CI"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  static_code_analysis:
    uses: sidkos/metadata_server/.github/workflows/static_code_analysis.yml@main
    with:
      build_and_install_script: "./scripts/build_and_install_open_api_client.sh"
    secrets: inherit

  openapi-validation:
    uses: sidkos/metadata_server/.github/workflows/openapi_validation_workflow.yml@main
    with:
      open_api_spec_file: "src/open_api_spec.yml"
    secrets: inherit
