name: 🔄 CI-CD

on:
  push:
  workflow_dispatch:

concurrency:
  group: 'CI-CD - ${{ github.workflow }} @ ${{ github.ref_name }}'
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: read
  packages: write

jobs:
#  ci:
#    name: 🛠️ CI
#    uses: sidkos/metadata_server/.github/workflows/ci.yml@add-client-buid
#    secrets: inherit
#
#  build-server-image:
#    name: 🏗️ 🖼️ Build Server Docker Image
#    needs: ci
#    uses: sidkos/metadata_server/.github/workflows/build_docker_image.yml@add-client-buid
#    with:
#      file: "Dockerfile"
#      image_name: "metadata_server"
#    secrets: inherit
#
#  build-openapi-client:
    name: 🧰 📦 Build & Publish OpenAPI Client
#    needs: ci
    uses: sidkos/metadata_server/.github/workflows/build_openapi_client_publish.yml@add-client-buid
    secrets: inherit
