---
name: 🛠️ Static Code Analysis

on:
  workflow_call:
    inputs:
      build_and_install_script:
        description: 'Path from the root of the repository to the script to build and install project the packages'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      build_and_install_script:
        description: 'Path from the root of the repository to the script to build and install project the packages'
        required: false
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  static-code-analysis:
    name: "🔍 📄 Static Code Analysis"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: SetUp Python Project
        uses: sidkos/metadata_server/.github/actions/setup_python_project@add-client-buid

      - name: Build and install client packages
        if: ${{ inputs.build_and_install_script }}
        run: ${{ inputs.build_and_install_script }}

      - name: Run Black
        if: always()
        uses: sidkos/metadata_server/.github/actions/black@add-client-buid

      - name: Run Isort
        if: always()
        uses: sidkos/metadata_server/.github/actions/isort@add-client-buid

      - name: Run Pycodestyle
        if: always()
        uses: sidkos/metadata_server/.github/actions/pycodestyle@add-client-buid

      - name: Run Flake8
        if: always()
        uses: sidkos/metadata_server/.github/actions/flake8@add-client-buid

      - name: Run MyPy
        if: always()
        uses: sidkos/metadata_server/.github/actions/mypy@add-client-buid

      - name: Run Yaml Lint
        if: always()
        uses: sidkos/metadata_server/.github/actions/yamllint@add-client-buid
